import type { Flashcard } from '@/types/db';

export const pl600Flashcards: Flashcard[] = [
  { "id": "p6-f1", "certId": "pl600", "topic": "Solution Envisioning", "front": "Fit-gap analysis", "back": "Process of comparing customer requirements against standard platform capabilities. Gaps are documented and assessed (OOB extension, customization, third-party, or accept gap).", "frontDe": "Fit-Gap-Analyse", "backDe": "Prozess des Vergleichs von Kundenanforderungen mit Standard-Plattformfähigkeiten. Lücken werden dokumentiert und bewertet (OOB-Erweiterung, Anpassung, Drittanbieter oder Lücke akzeptieren)." },
  { "id": "p6-f2", "certId": "pl600", "topic": "Solution Envisioning", "front": "When NOT to use Power Platform", "back": "Sub-millisecond latency requirements, high-frequency financial trading, massive data processing at millions of events/sec, or complex real-time ML inference — use Azure-native services instead.", "frontDe": "Wann Power Platform NICHT verwendet werden soll", "backDe": "Sub-Millisekunden-Latenzanforderungen, Hochfrequenzhandel, massive Datenverarbeitung mit Millionen von Ereignissen/Sek. oder komplexe Echtzeit-ML-Inferenz — stattdessen Azure-native Dienste verwenden." },
  { "id": "p6-f3", "certId": "pl600", "topic": "Security Architecture", "front": "Business unit (BU) in Dataverse", "back": "Defines data ownership and access scope. Users only see records in their own BU (and child BUs based on security role depth). Used for organizational data isolation.", "frontDe": "Business Unit (BU) in Dataverse", "backDe": "Definiert Dateneigentum und Zugriffsbereich. Benutzer sehen nur Datensätze in ihrer eigenen BU (und untergeordneten BUs basierend auf Sicherheitsrollen-Tiefe). Für organisatorische Datenisolation verwendet." },
  { "id": "p6-f4", "certId": "pl600", "topic": "Security Architecture", "front": "Record sharing vs. security roles", "back": "Security roles: broad, role-based access. Record sharing: targeted, temporary access to specific records — least-privilege approach for cross-BU access without role changes.", "frontDe": "Datensatzfreigabe vs. Sicherheitsrollen", "backDe": "Sicherheitsrollen: breit, rollenbasierter Zugriff. Datensatzfreigabe: gezielt, temporärer Zugriff auf bestimmte Datensätze — Least-Privilege-Ansatz für BU-übergreifenden Zugriff ohne Rollenänderungen." },
  { "id": "p6-f5", "certId": "pl600", "topic": "Security Architecture", "front": "Hierarchy security", "back": "Provides managers automatic read (or read+write) access to records owned by their direct reports and subordinates — based on manager-employee or position hierarchy.", "frontDe": "Hierarchiesicherheit", "backDe": "Gibt Managern automatischen Lese- (oder Lese+Schreib-)Zugriff auf Datensätze, die direkte Berichte und Untergeordnete besitzen — basierend auf Manager-Mitarbeiter- oder Positionshierarchie." },
  { "id": "p6-f6", "certId": "pl600", "topic": "Security Architecture", "front": "DLP (Data Loss Prevention) policies", "back": "Classify connectors into Business, Non-Business, or Blocked tiers. Prevent certain connector combinations (e.g., Dataverse + Gmail) in the same flow.", "frontDe": "DLP (Data Loss Prevention)-Richtlinien", "backDe": "Klassifizieren Connectors in Business-, Non-Business- oder Blockierte Stufen. Verhindern bestimmte Connector-Kombinationen (z.B. Dataverse + Gmail) im selben Flow." },
  { "id": "p6-f7", "certId": "pl600", "topic": "Security Architecture", "front": "Activity logging vs. Dataverse auditing", "back": "Dataverse auditing: tracks data changes (create/update/delete) with old/new values. Activity logging (M365 audit log): tracks read/view events — who accessed a record without changing it.", "frontDe": "Aktivitätsprotokollierung vs. Dataverse-Überwachung", "backDe": "Dataverse-Überwachung: verfolgt Datenänderungen (Erstellen/Aktualisieren/Löschen) mit alten/neuen Werten. Aktivitätsprotokollierung (M365-Überwachungsprotokoll): verfolgt Lese-/Anzeigeereignisse — wer auf einen Datensatz zugegriffen hat, ohne ihn zu ändern." },
  { "id": "p6-f8", "certId": "pl600", "topic": "Data Architecture", "front": "Dataverse vs. Azure SQL for large data", "back": "Dataverse: rich API, security, business rules — expensive per GB, not for bulk archival. Azure SQL: cheaper at scale, no native Power Platform integration — requires custom connectors.", "frontDe": "Dataverse vs. Azure SQL für große Daten", "backDe": "Dataverse: reichhaltige API, Sicherheit, Geschäftsregeln — teuer pro GB, nicht für Bulk-Archivierung. Azure SQL: günstiger bei Skalierung, keine native Power Platform-Integration — erfordert benutzerdefinierte Connectors." },
  { "id": "p6-f9", "certId": "pl600", "topic": "Data Architecture", "front": "Azure Synapse Link for Dataverse", "back": "Continuously exports Dataverse data to Azure Data Lake in near real time. Enables large-scale analytics and archival without impacting Dataverse performance.", "frontDe": "Azure Synapse Link für Dataverse", "backDe": "Exportiert Dataverse-Daten kontinuierlich und nahezu in Echtzeit in Azure Data Lake. Ermöglicht groß angelegte Analysen und Archivierung ohne Beeinträchtigung der Dataverse-Leistung." },
  { "id": "p6-f10", "certId": "pl600", "topic": "Data Architecture", "front": "Change tracking for data warehouse sync", "back": "Dataverse feature that returns only records changed since a given delta token. Handles deletes. More reliable than timestamp filtering for incremental data warehouse sync.", "frontDe": "Änderungsverfolgung für Data-Warehouse-Sync", "backDe": "Dataverse-Funktion, die nur Datensätze zurückgibt, die sich seit einem gegebenen Delta-Token geändert haben. Behandelt Löschungen. Zuverlässiger als Zeitstempel-Filterung für inkrementelle Data-Warehouse-Synchronisierung." },
  { "id": "p6-f11", "certId": "pl600", "topic": "Data Architecture", "front": "Dataverse search (Relevance Search)", "back": "Azure Cognitive Search-powered full-text search across all indexed Dataverse tables simultaneously. Near-real-time indexing, relevance ranking — replaces Quick Find for large environments.", "frontDe": "Dataverse-Suche (Relevanzsuche)", "backDe": "Von Azure Cognitive Search betriebene Volltextsuche über alle indizierten Dataverse-Tabellen gleichzeitig. Nahezu Echtzeit-Indizierung, Relevanzranking — ersetzt Quick Find für große Umgebungen." },
  { "id": "p6-f12", "certId": "pl600", "topic": "Integration Architecture", "front": "Service Bus Queue vs. Event Hubs", "back": "Service Bus Queue: ordered delivery (FIFO), retry, dead-letter, low-to-medium volume. Event Hubs: high-throughput streaming, partitioned, no FIFO guarantee, for millions of events/sec.", "frontDe": "Service Bus Queue vs. Event Hubs", "backDe": "Service Bus Queue: geordnete Lieferung (FIFO), Wiederholung, Dead-Letter, niedriges bis mittleres Volumen. Event Hubs: Hochdurchsatz-Streaming, partitioniert, keine FIFO-Garantie, für Millionen von Ereignissen/Sek." },
  { "id": "p6-f13", "certId": "pl600", "topic": "Integration Architecture", "front": "Bidirectional sync loop prevention", "back": "Tag each synced record with its source system. When the sync job processes a record, skip propagation if the record originated from the other system — breaks the infinite loop.", "frontDe": "Bidirektionale Sync-Schleifen-Prävention", "backDe": "Jeden synchronisierten Datensatz mit seinem Quellsystem kennzeichnen. Wenn der Sync-Job einen Datensatz verarbeitet, Weitergabe überspringen, wenn der Datensatz aus dem anderen System stammte — bricht die endlose Schleife." },
  { "id": "p6-f14", "certId": "pl600", "topic": "ALM & Governance", "front": "Managed properties in solutions", "back": "Control whether managed solution components (forms, tables, fields) can be customized in target environments. Set 'Allow customizations' to false to lock components.", "frontDe": "Verwaltete Eigenschaften in Lösungen", "backDe": "Steuern, ob verwaltete Lösungskomponenten (Formulare, Tabellen, Felder) in Zielumgebungen angepasst werden können. 'Anpassungen zulassen' auf false setzen, um Komponenten zu sperren." },
  { "id": "p6-f15", "certId": "pl600", "topic": "ALM & Governance", "front": "Environment strategy: Dev → Test → Prod", "back": "Developer envs (individual, free) → Shared sandbox (integration testing, UAT with production data copy) → Production (live data, SLA, never for development).", "frontDe": "Umgebungsstrategie: Entwicklung → Test → Produktion", "backDe": "Entwicklerumgebungen (individuell, kostenlos) → Gemeinsame Sandbox (Integrationstests, UAT mit Produktionsdatenkopie) → Produktion (Live-Daten, SLA, nie für Entwicklung)." },
  { "id": "p6-f16", "certId": "pl600", "topic": "ALM & Governance", "front": "pac solution unpack (Power Platform CLI)", "back": "Extracts a solution .zip into individual XML/JSON files per component. Produces diff-friendly files for Git source control — the standard for CI/CD with Power Platform.", "frontDe": "pac solution unpack (Power Platform CLI)", "backDe": "Extrahiert eine Lösungs-.zip in einzelne XML/JSON-Dateien pro Komponente. Erzeugt diff-freundliche Dateien für Git-Quellcodeverwaltung — der Standard für CI/CD mit Power Platform." },
  { "id": "p6-f17", "certId": "pl600", "topic": "ALM & Governance", "front": "Power Platform Build Tools for Azure DevOps", "back": "Azure DevOps tasks for automating Power Platform CI/CD: export solution, unpack, solution checker, import, run test flows, publish. Enables automated testing after deployment.", "frontDe": "Power Platform Build Tools für Azure DevOps", "backDe": "Azure DevOps-Aufgaben zur Automatisierung von Power Platform CI/CD: Lösung exportieren, entpacken, Solution Checker, importieren, Test-Flows ausführen, veröffentlichen. Ermöglicht automatisierte Tests nach der Bereitstellung." },
  { "id": "p6-f18", "certId": "pl600", "topic": "Analytics", "front": "Power BI vs. model-driven app dashboards", "back": "Power BI: self-service, trend analysis, external sharing, ad-hoc reports — for analytics. Model-driven dashboards: simple charts tied to Dataverse, require Dataverse license, no external sharing.", "frontDe": "Power BI vs. modellgesteuerte App-Dashboards", "backDe": "Power BI: Self-Service, Trendanalyse, externe Freigabe, Ad-hoc-Berichte — für Analysen. Modellgesteuerte Dashboards: einfache Diagramme, an Dataverse gebunden, erfordern Dataverse-Lizenz, keine externe Freigabe." },
  { "id": "p6-f19", "certId": "pl600", "topic": "Automation Architecture", "front": "Copilot Studio use cases", "back": "Conversational AI chatbots and virtual agents. Use for: Q&A on knowledge bases, guided customer service, FAQ automation. NOT for: event-triggered workflows (use Power Automate instead).", "frontDe": "Copilot Studio Anwendungsfälle", "backDe": "Konversationelle KI-Chatbots und virtuelle Agenten. Verwenden für: Q&A auf Wissensdatenbanken, geführten Kundenservice, FAQ-Automatisierung. NICHT für: ereignisgesteuerte Workflows (stattdessen Power Automate verwenden)." },
  { "id": "p6-f20", "certId": "pl600", "topic": "Automation Architecture", "front": "RPA (Robotic Process Automation)", "back": "Power Automate desktop flows automate UI interactions with legacy apps that have no API. Can be triggered from cloud flows. Use when API access is not available.", "frontDe": "RPA (Robotic Process Automation)", "backDe": "Power Automate Desktop-Flows automatisieren UI-Interaktionen mit Legacy-Apps ohne API. Können von Cloud-Flows ausgelöst werden. Verwenden, wenn API-Zugriff nicht verfügbar ist." },
  { "id": "p6-f21", "certId": "pl600", "topic": "Data Architecture", "front": "SharePoint integration with Dataverse", "back": "Links SharePoint document libraries to Dataverse records. Files stored in SharePoint (large file support, versioning, collaboration) with metadata linked to the Dataverse record.", "frontDe": "SharePoint-Integration mit Dataverse", "backDe": "Verknüpft SharePoint-Dokumentbibliotheken mit Dataverse-Datensätzen. Dateien in SharePoint gespeichert (große Dateiunterstützung, Versionierung, Zusammenarbeit) mit Metadaten, die mit dem Dataverse-Datensatz verknüpft sind." },
  { "id": "p6-f22", "certId": "pl600", "topic": "Solution Architecture", "front": "Model-driven app vs. Canvas app — when to choose", "back": "Model-driven: complex data management, relationship navigation, security roles, auto-generated UI — for internal power users. Canvas: custom UI, simple data, external users, offline — for tailored UX.", "frontDe": "Modellgesteuerte App vs. Canvas App — wann welche wählen", "backDe": "Modellgesteuert: komplexes Datenmanagement, Beziehungsnavigation, Sicherheitsrollen, auto-generierte UI — für interne Power-User. Canvas: benutzerdefinierte UI, einfache Daten, externe Benutzer, offline — für maßgeschneiderte UX." },
  { "id": "p6-f23", "certId": "pl600", "topic": "Security Architecture", "front": "Dataverse security model layers", "back": "1. Organization-level: env access. 2. BU ownership: which records visible. 3. Security role depth: org/BU/team/personal. 4. Field-level security: column access. 5. Record sharing: individual access.", "frontDe": "Dataverse-Sicherheitsmodell-Schichten", "backDe": "1. Organisationsebene: Umgebungszugriff. 2. BU-Eigentum: welche Datensätze sichtbar. 3. Sicherheitsrollen-Tiefe: Org/BU/Team/Persönlich. 4. Feldebenensicherheit: Spaltenzugriff. 5. Datensatzfreigabe: individueller Zugriff." },
  { "id": "p6-f24", "certId": "pl600", "topic": "Integration Architecture", "front": "Integration classification dimensions", "back": "Volume (data quantity), Volatility (change frequency), Time sensitivity (latency requirements), Regulated (compliance/geo restrictions), Licensed (copyrighted data).", "frontDe": "Integrations-Klassifizierungsdimensionen", "backDe": "Volumen (Datenmenge), Volatilität (Änderungshäufigkeit), Zeitkritisch (Latenzanforderungen), Reguliert (Compliance/Geo-Einschränkungen), Lizenziert (urheberrechtlich geschützte Daten)." },
  { "id": "p6-f25", "certId": "pl600", "topic": "Solution Envisioning", "front": "Industry accelerators", "back": "Pre-built Dataverse data models for specific verticals: Automotive (fleet), Healthcare (patient), Nonprofit (grants), Financial Services, Education. Reduces time-to-value for domain-specific solutions.", "frontDe": "Branchenbeschleuniger (Industry Accelerators)", "backDe": "Vorgefertigte Dataverse-Datenmodelle für spezifische Branchen: Automotive (Flotte), Gesundheitswesen (Patient), Nonprofit (Förderungen), Finanzdienstleistungen, Bildung. Reduziert Time-to-Value für branchenspezifische Lösungen." }
];
