import type { GlossaryTerm } from '@/types/db';

export const pl600GlossaryTerms: GlossaryTerm[] = [
  { "term": "Fit-gap analysis", "certId": "pl600", "definition": "An architectural technique for comparing customer requirements against platform capabilities. Gaps are documented and assessed with options: OOB configuration, extension, customization, third-party, or accept the gap.", "definitionDe": "Eine Architekturtechnik zum Vergleich von Kundenanforderungen mit Plattformfähigkeiten. Lücken werden dokumentiert und mit Optionen bewertet: OOB-Konfiguration, Erweiterung, Anpassung, Drittanbieter oder Lücke akzeptieren." },
  { "term": "Solution architect (PL-600)", "certId": "pl600", "definition": "A role responsible for the overall vision, design, and architecture of a Power Platform solution. Translates business requirements into technical architecture decisions across data, security, integration, analytics, and ALM.", "definitionDe": "Eine Rolle, die für die Gesamtvision, das Design und die Architektur einer Power Platform-Lösung verantwortlich ist. Übersetzt Geschäftsanforderungen in technische Architekturentscheidungen über Daten, Sicherheit, Integration, Analysen und ALM." },
  { "term": "Industry accelerator", "certId": "pl600", "definition": "Pre-built Dataverse data model packages for specific verticals (Automotive, Healthcare, Nonprofit, Financial Services, Education). Accelerates data model creation by providing common industry schemas.", "definitionDe": "Vorgefertigte Dataverse-Datenmodellpakete für spezifische Branchen (Automotive, Gesundheitswesen, Nonprofit, Finanzdienstleistungen, Bildung). Beschleunigt die Datenmodellerstellung durch Bereitstellung gemeinsamer Branchenschemata." },
  { "term": "Business unit (BU)", "certId": "pl600", "definition": "A Dataverse security boundary that defines data ownership. Users can only access records owned by their BU (and child BUs based on security role depth). Used to model organizational data isolation.", "definitionDe": "Eine Dataverse-Sicherheitsgrenze, die das Dateneigentum definiert. Benutzer können nur auf Datensätze zugreifen, die ihrer BU gehören (und untergeordneten BUs basierend auf Sicherheitsrollen-Tiefe). Wird verwendet, um organisatorische Datenisolation zu modellieren." },
  { "term": "Hierarchy security", "certId": "pl600", "definition": "A Dataverse feature that grants managers automatic read (or read+write) access to records owned by their direct reports and subordinates, based on manager-employee or position hierarchy configuration.", "definitionDe": "Eine Dataverse-Funktion, die Managern automatischen Lese- (oder Lese+Schreib-)Zugriff auf Datensätze gewährt, die direkte Berichte und Untergeordnete besitzen, basierend auf der Manager-Mitarbeiter- oder Positionshierarchie-Konfiguration." },
  { "term": "DLP (Data Loss Prevention) policy", "certId": "pl600", "definition": "A Power Platform governance feature that classifies connectors into Business, Non-Business, or Blocked tiers. Prevents flows from mixing business data connectors (e.g., Dataverse) with personal/unapproved connectors (e.g., Gmail).", "definitionDe": "Eine Power Platform-Governance-Funktion, die Connectors in Business-, Non-Business- oder Blockierte Stufen klassifiziert. Verhindert, dass Flows Geschäftsdaten-Connectors (z.B. Dataverse) mit persönlichen/nicht genehmigten Connectors (z.B. Gmail) mischen." },
  { "term": "Managed property", "certId": "pl600", "definition": "A setting on a managed solution component that controls whether target environment makers can customize that component. Setting 'Allow customizations' to false locks the component after deployment.", "definitionDe": "Eine Einstellung auf einer verwalteten Lösungskomponente, die steuert, ob Maker in der Zielumgebung diese Komponente anpassen können. Das Setzen von 'Anpassungen zulassen' auf false sperrt die Komponente nach der Bereitstellung." },
  { "term": "Azure Synapse Link for Dataverse", "certId": "pl600", "definition": "A Power Platform feature that continuously exports Dataverse data to Azure Data Lake Storage in near real time. Enables large-scale analytics, archival, and integration with Azure Synapse Analytics without impacting Dataverse performance.", "definitionDe": "Eine Power Platform-Funktion, die Dataverse-Daten kontinuierlich und nahezu in Echtzeit in Azure Data Lake Storage exportiert. Ermöglicht groß angelegte Analysen, Archivierung und Integration mit Azure Synapse Analytics ohne Beeinträchtigung der Dataverse-Leistung." },
  { "term": "Change tracking (Dataverse)", "certId": "pl600", "definition": "A Dataverse feature that tracks all changes (create, update, delete) to enabled tables since a given delta token. Used for efficient incremental data synchronization with external systems like data warehouses.", "definitionDe": "Eine Dataverse-Funktion, die alle Änderungen (Erstellen, Aktualisieren, Löschen) an aktivierten Tabellen seit einem gegebenen Delta-Token verfolgt. Für eine effiziente inkrementelle Datensynchronisierung mit externen Systemen wie Data Warehouses verwendet." },
  { "term": "Dataverse search", "certId": "pl600", "definition": "Azure Cognitive Search-powered full-text search in Dataverse that searches across all indexed tables simultaneously with relevance ranking. Replaces Quick Find for large environments with millions of records.", "definitionDe": "Von Azure Cognitive Search betriebene Volltextsuche in Dataverse, die gleichzeitig alle indizierten Tabellen mit Relevanzranking durchsucht. Ersetzt Quick Find für große Umgebungen mit Millionen von Datensätzen." },
  { "term": "RPA (Robotic Process Automation)", "certId": "pl600", "definition": "Automation of UI-based interactions with software that has no API. In Power Platform, implemented via Power Automate desktop flows — the correct approach for legacy application integration.", "definitionDe": "Automatisierung von UI-basierten Interaktionen mit Software ohne API. In Power Platform über Power Automate Desktop-Flows implementiert — der richtige Ansatz für die Integration von Legacy-Anwendungen." },
  { "term": "Copilot Studio", "certId": "pl600", "definition": "Microsoft's low-code platform for building conversational AI agents and chatbots. Can connect to knowledge sources (SharePoint, websites, Dataverse) for generative AI-powered answers. Replaces Power Virtual Agents.", "definitionDe": "Microsofts Low-Code-Plattform zum Erstellen konversationeller KI-Agenten und Chatbots. Kann sich mit Wissensquellen (SharePoint, Websites, Dataverse) für generative KI-gestützte Antworten verbinden. Ersetzt Power Virtual Agents." },
  { "term": "Power Platform Build Tools", "certId": "pl600", "definition": "Azure DevOps tasks that automate Power Platform CI/CD pipelines: export/import solutions, solution checker, publish customizations, run test flows. The standard for automated deployment pipelines.", "definitionDe": "Azure DevOps-Aufgaben, die Power Platform CI/CD-Pipelines automatisieren: Lösungen exportieren/importieren, Solution Checker, Anpassungen veröffentlichen, Test-Flows ausführen. Der Standard für automatisierte Bereitstellungspipelines." },
  { "term": "Activity logging", "certId": "pl600", "definition": "Logs record view/read events to the Microsoft 365 unified audit log — tracking who accessed a Dataverse record even when no changes were made. Complementary to Dataverse auditing (which tracks writes only).", "definitionDe": "Protokolliert Datensatzanzeige-/Leseereignisse im Microsoft 365 unified audit log — verfolgt, wer auf einen Dataverse-Datensatz zugegriffen hat, auch wenn keine Änderungen vorgenommen wurden. Ergänzend zur Dataverse-Überwachung (die nur Schreibvorgänge verfolgt)." },
  { "term": "Sandbox environment", "certId": "pl600", "definition": "A Power Platform environment type for testing and UAT. Can be seeded with a copy of production data, reset after testing, and isolated from live systems. The correct environment for UAT with business users.", "definitionDe": "Ein Power Platform-Umgebungstyp für Tests und UAT. Kann mit einer Kopie der Produktionsdaten befüllt, nach dem Test zurückgesetzt und von Live-Systemen isoliert werden. Die richtige Umgebung für UAT mit Geschäftsbenutzern." },
  { "term": "Connection reference", "certId": "pl600", "definition": "A Power Platform solution component that decouples connector credentials from flow/app logic. Allows different users or service principals to own connections per environment without modifying the flow.", "definitionDe": "Eine Power Platform-Lösungskomponente, die Connector-Anmeldeinformationen von Flow-/App-Logik entkoppelt. Ermöglicht es verschiedenen Benutzern oder Service Principals, Verbindungen pro Umgebung zu besitzen, ohne den Flow zu ändern." },
  { "term": "pac solution unpack", "certId": "pl600", "definition": "A Power Platform CLI command that extracts a solution .zip into individual XML/JSON files per component — enabling meaningful Git diffs and source control for Power Platform solutions.", "definitionDe": "Ein Power Platform CLI-Befehl, der eine Lösungs-.zip in einzelne XML/JSON-Dateien pro Komponente extrahiert — ermöglicht aussagekräftige Git-Diffs und Quellcodeverwaltung für Power Platform-Lösungen." },
  { "term": "Azure Service Bus (queue vs. topic)", "certId": "pl600", "definition": "Queue: point-to-point, FIFO, one consumer, retry, dead-letter. Topic: pub/sub, multiple subscribers via subscriptions. Both provide asynchronous, guaranteed delivery — unlike Azure Relay (synchronous).", "definitionDe": "Queue: Punkt-zu-Punkt, FIFO, ein Verbraucher, Wiederholung, Dead-Letter. Topic: Pub/Sub, mehrere Abonnenten über Abonnements. Beide bieten asynchrone, garantierte Lieferung — im Gegensatz zu Azure Relay (synchron)." },
  { "term": "Common Data Model (CDM)", "certId": "pl600", "definition": "An open-source specification of standard business data schemas maintained by Microsoft. Core entities include Account, Contact, Task. Industry accelerators extend CDM with vertical-specific schemas.", "definitionDe": "Eine Open-Source-Spezifikation von Standard-Geschäftsdatenschemata, die von Microsoft gepflegt wird. Kernentitäten umfassen Konto, Kontakt, Aufgabe. Branchenbeschleuniger erweitern CDM mit vertikalspezifischen Schemas." },
  { "term": "Power BI embedded in Power Platform", "certId": "pl600", "definition": "Power BI reports can be embedded in model-driven app dashboards and Power Pages portals. Provides rich analytics inside Power Platform apps without navigating to Power BI service separately.", "definitionDe": "Power BI-Berichte können in modellgesteuerte App-Dashboards und Power Pages-Portale eingebettet werden. Bietet umfangreiche Analysen innerhalb von Power Platform-Apps ohne separate Navigation zum Power BI-Dienst." }
];
