import type { Flashcard } from '@/types/db';

export const pl400Flashcards: Flashcard[] = [
  { "id": "p4-f1", "certId": "pl400", "topic": "ALM", "front": "Managed vs Unmanaged solution", "back": "Managed: components locked in target env, supports clean uninstall. Unmanaged: fully editable, used in development.", "frontDe": "Verwaltete vs. nicht verwaltete Lösung", "backDe": "Verwaltet: Komponenten in Zielumgebung gesperrt, saubere Deinstallation möglich. Nicht verwaltet: vollständig bearbeitbar, für Entwicklung verwendet." },
  { "id": "p4-f2", "certId": "pl400", "topic": "ALM", "front": "Power Platform Pipelines vs ALM Accelerator", "back": "Pipelines: built-in, no-code, Microsoft's recommended default. ALM Accelerator: open-source tool on Azure DevOps, more powerful but complex.", "frontDe": "Power Platform Pipelines vs. ALM Accelerator", "backDe": "Pipelines: eingebaut, codelose, Microsofts empfohlener Standard. ALM Accelerator: Open-Source-Tool auf Azure DevOps, leistungsfähiger aber komplexer." },
  { "id": "p4-f3", "certId": "pl400", "topic": "ALM", "front": "Environment variable", "back": "Solution component that stores configuration values (string, number, secret) that differ per environment. Overridden at deploy time without code changes.", "frontDe": "Umgebungsvariable", "backDe": "Lösungskomponente, die Konfigurationswerte (Zeichenfolge, Zahl, Secret) speichert, die sich pro Umgebung unterscheiden. Wird zum Bereitstellungszeitpunkt ohne Codeänderungen überschrieben." },
  { "id": "p4-f4", "certId": "pl400", "topic": "ALM", "front": "Solution layers", "back": "Active (unmanaged) layer always takes precedence over managed layers. Updating a managed solution won't override an active customization on top.", "frontDe": "Lösungsschichten", "backDe": "Aktive (nicht verwaltete) Schicht hat immer Vorrang vor verwalteten Schichten. Das Aktualisieren einer verwalteten Lösung überschreibt keine aktive Anpassung darüber." },
  { "id": "p4-f5", "certId": "pl400", "topic": "ALM", "front": "Power Platform environment types", "back": "Developer: free, personal, for dev. Sandbox: testing/UAT, can be reset. Production: live data, SLA. Trial: 30-day eval.", "frontDe": "Power Platform-Umgebungstypen", "backDe": "Entwickler: kostenlos, persönlich, für Entwicklung. Sandbox: Test/UAT, kann zurückgesetzt werden. Produktion: Live-Daten, SLA. Trial: 30-Tage-Evaluierung." },
  { "id": "p4-f6", "certId": "pl400", "topic": "Plug-ins", "front": "Plug-in execution stages", "back": "Stage 10 Pre-Validation: before security, outside TX. Stage 20 Pre-Operation: before DB write, inside TX. Stage 40 Post-Operation: after DB write, sync or async.", "frontDe": "Plug-in-Ausführungsstufen", "backDe": "Stufe 10 Pre-Validation: vor Sicherheit, außerhalb TX. Stufe 20 Pre-Operation: vor DB-Schreiben, in TX. Stufe 40 Post-Operation: nach DB-Schreiben, sync oder async." },
  { "id": "p4-f7", "certId": "pl400", "topic": "Plug-ins", "front": "IOrganizationService", "back": "Core Dataverse SDK interface for CRUD: Create, Retrieve, RetrieveMultiple, Update, Delete, Execute, Associate, Disassociate.", "frontDe": "IOrganizationService", "backDe": "Kern-Dataverse-SDK-Interface für CRUD: Create, Retrieve, RetrieveMultiple, Update, Delete, Execute, Associate, Disassociate." },
  { "id": "p4-f8", "certId": "pl400", "topic": "Plug-ins", "front": "IPluginExecutionContext", "back": "Provides event metadata: entity name, message (Create/Update/Delete), primary entity Id, input/output parameters, depth, initiating user.", "frontDe": "IPluginExecutionContext", "backDe": "Stellt Ereignis-Metadaten bereit: Entitätsname, Nachricht (Create/Update/Delete), primäre Entitäts-ID, Ein-/Ausgabeparameter, Tiefe, initiierender Benutzer." },
  { "id": "p4-f9", "certId": "pl400", "topic": "Plug-ins", "front": "How to roll back a plug-in operation", "back": "Register synchronously on Pre-Operation (stage 20) and throw InvalidPluginExecutionException — rolls back the entire database transaction.", "frontDe": "Wie man eine Plug-in-Operation zurückrollt", "backDe": "Synchron auf Pre-Operation (Stufe 20) registrieren und InvalidPluginExecutionException werfen — rollt die gesamte Datenbanktransaktion zurück." },
  { "id": "p4-f10", "certId": "pl400", "topic": "PCF", "front": "PCF component types", "back": "Field component: binds to a single column value. Dataset component: receives a collection of records (replaces grids/views).", "frontDe": "PCF-Komponententypen", "backDe": "Feld-Komponente: bindet an einen einzelnen Spaltenwert. Dataset-Komponente: empfängt eine Sammlung von Datensätzen (ersetzt Gitter/Ansichten)." },
  { "id": "p4-f11", "certId": "pl400", "topic": "PCF", "front": "What is Power Apps Component Framework (PCF)?", "back": "Framework for building custom controls (in TypeScript/React) that integrate natively into canvas and model-driven apps — can replace fields, grids, and subgrids.", "frontDe": "Was ist das Power Apps Component Framework (PCF)?", "backDe": "Framework zum Erstellen benutzerdefinierter Steuerelemente (in TypeScript/React), die nativ in Canvas- und modellgesteuerte Apps integriert werden — kann Felder, Gitter und Subgitter ersetzen." },
  { "id": "p4-f12", "certId": "pl400", "topic": "Dataverse", "front": "Alternate keys in Dataverse", "back": "Let you identify records by business keys (email, product code) instead of GUIDs. Enables upsert in one request without a prior lookup.", "frontDe": "Alternative Schlüssel in Dataverse", "backDe": "Ermöglichen die Identifizierung von Datensätzen anhand von Geschäftsschlüsseln (E-Mail, Produktcode) anstatt GUIDs. Ermöglicht Upsert in einer Anfrage ohne vorherige Suche." },
  { "id": "p4-f13", "certId": "pl400", "topic": "Dataverse", "front": "Virtual tables", "back": "Present external data as Dataverse tables without storing it locally. Use a data provider to delegate reads/writes to the external system.", "frontDe": "Virtuelle Tabellen", "backDe": "Stellen externe Daten als Dataverse-Tabellen dar, ohne sie lokal zu speichern. Verwenden einen Datenanbieter, um Lese-/Schreiboperationen an das externe System zu delegieren." },
  { "id": "p4-f14", "certId": "pl400", "topic": "Dataverse", "front": "Field-level security (FLS)", "back": "Column security profiles restrict read/create/update on individual columns, independent of table-level security roles.", "frontDe": "Feldebenensicherheit (FLS)", "backDe": "Spaltensicherheitsprofile schränken Lesen/Erstellen/Aktualisieren einzelner Spalten ein, unabhängig von Sicherheitsrollen auf Tabellenebene." },
  { "id": "p4-f15", "certId": "pl400", "topic": "Dataverse", "front": "Dataverse relationship cascade behaviors", "back": "Parental: cascades all (including delete). Referential: cascades assign/share, NOT delete (orphans). Referential Restrict Delete: prevents parent deletion when children exist.", "frontDe": "Dataverse Beziehungs-Kaskadenverhalten", "backDe": "Übergeordnet: kaskadiert alles (inkl. Löschen). Referentiell: kaskadiert Zuweisen/Freigeben, NICHT Löschen (Waisen). Referentiell Löschen einschränken: verhindert übergeordnetes Löschen wenn Kinder vorhanden." },
  { "id": "p4-f16", "certId": "pl400", "topic": "Dataverse", "front": "Dataverse auditing — three levels", "back": "1) Enable at environment level, 2) Enable on each table, 3) Enable on each column. All three must be active to capture field-level changes.", "frontDe": "Dataverse-Überwachung — drei Ebenen", "backDe": "1) Auf Umgebungsebene aktivieren, 2) Auf jeder Tabelle aktivieren, 3) Auf jeder Spalte aktivieren. Alle drei müssen aktiv sein, um Änderungen auf Feldebene zu erfassen." },
  { "id": "p4-f17", "certId": "pl400", "topic": "Integration", "front": "Web API upsert", "back": "HTTP PATCH request with an alternate key: creates the record if it doesn't exist, updates it if it does — in a single request.", "frontDe": "Web API Upsert", "backDe": "HTTP PATCH-Anfrage mit alternativem Schlüssel: erstellt den Datensatz, wenn er nicht existiert, aktualisiert ihn, wenn er existiert — in einer einzigen Anfrage." },
  { "id": "p4-f18", "certId": "pl400", "topic": "Integration", "front": "OData query options for Dataverse Web API", "back": "$select: limit columns. $filter: filter rows (WHERE). $expand: include related data (JOIN). $orderby: sort. $top: limit count.", "frontDe": "OData-Abfrageoptionen für Dataverse Web API", "backDe": "$select: Spalten begrenzen. $filter: Zeilen filtern (WHERE). $expand: verwandte Daten einbeziehen (JOIN). $orderby: sortieren. $top: Anzahl begrenzen." },
  { "id": "p4-f19", "certId": "pl400", "topic": "Integration", "front": "Azure Relay vs Service Bus Queue", "back": "Relay: synchronous, caller waits for response (request/reply). Service Bus Queue: asynchronous, fire-and-forget with guaranteed delivery.", "frontDe": "Azure Relay vs. Service Bus Queue", "backDe": "Relay: synchron, Aufrufer wartet auf Antwort (Request/Reply). Service Bus Queue: asynchron, Feuer-und-Vergessen mit garantierter Lieferung." },
  { "id": "p4-f20", "certId": "pl400", "topic": "Integration", "front": "On-premises data gateway", "back": "Agent installed on a local machine that bridges Power Platform cloud services to on-premises data sources (SQL Server, SharePoint, Oracle) behind firewalls.", "frontDe": "Lokales Datengateway", "backDe": "Agent, der auf einem lokalen Computer installiert ist und Power Platform-Cloud-Dienste mit lokalen Datenquellen (SQL Server, SharePoint, Oracle) hinter Firewalls verbindet." },
  { "id": "p4-f21", "certId": "pl400", "topic": "Power Automate", "front": "Power Automate flow types", "back": "Automated: event-triggered. Scheduled: recurrence-triggered. Instant: manually triggered. Desktop: UI automation for legacy apps.", "frontDe": "Power Automate Flow-Typen", "backDe": "Automatisiert: ereignisgesteuert. Geplant: wiederholungsgesteuert. Sofort: manuell ausgelöst. Desktop: UI-Automatisierung für Legacy-Apps." },
  { "id": "p4-f22", "certId": "pl400", "topic": "Power Automate", "front": "Run-after configuration in Power Automate", "back": "Controls whether a step executes based on the prior action's outcome: succeeded, failed, timed out, or skipped. Used to implement error handling.", "frontDe": "Ausführen-nach-Konfiguration in Power Automate", "backDe": "Steuert, ob ein Schritt basierend auf dem Ergebnis der vorherigen Aktion ausgeführt wird: erfolgreich, fehlgeschlagen, Zeitüberschreitung oder übersprungen. Für Fehlerbehandlung verwendet." },
  { "id": "p4-f23", "certId": "pl400", "topic": "Power Apps", "front": "Delegation in canvas apps", "back": "Delegation = filter/sort processed by the data source (server-side). Non-delegable functions fall back to client-side with a 500-record limit, silently truncating results.", "frontDe": "Delegation in Canvas Apps", "backDe": "Delegation = Filter/Sortierung vom Datenquelle verarbeitet (serverseitig). Nicht delegierbare Funktionen fallen auf clientseitige Verarbeitung mit 500-Datensatz-Limit zurück, Ergebnisse werden still abgeschnitten." },
  { "id": "p4-f24", "certId": "pl400", "topic": "Power Apps", "front": "Canvas app offline mode", "back": "Only the Dataverse connector supports native offline mode in canvas apps. Data is cached on-device and synced when connectivity is restored.", "frontDe": "Canvas App Offline-Modus", "backDe": "Nur der Dataverse-Connector unterstützt den nativen Offline-Modus in Canvas Apps. Daten werden auf dem Gerät zwischengespeichert und synchronisiert, wenn die Verbindung wiederhergestellt wird." },
  { "id": "p4-f25", "certId": "pl400", "topic": "AI Builder", "front": "AI Builder model types for documents", "back": "Document processing: extracts fields from forms/invoices (semi-structured). Text recognition (OCR): extracts raw text. Entity extraction: finds named entities in free text.", "frontDe": "AI Builder-Modelltypen für Dokumente", "backDe": "Dokumentenverarbeitung: extrahiert Felder aus Formularen/Rechnungen (halbstrukturiert). Texterkennung (OCR): extrahiert Rohtext. Entitätsextraktion: findet benannte Entitäten in Freitext." }
];
