import type { GlossaryTerm } from '@/types/db';

export const pl400GlossaryTerms: GlossaryTerm[] = [
  { "term": "PCF (Power Apps Component Framework)", "certId": "pl400", "definition": "A framework for building custom controls in TypeScript/React that integrate natively into canvas and model-driven apps, replacing standard fields, grids, and subgrids.", "definitionDe": "Ein Framework zum Erstellen benutzerdefinierter Steuerelemente in TypeScript/React, die nativ in Canvas- und modellgesteuerte Apps integriert werden und Standard-Felder, Gitter und Subgitter ersetzen." },
  { "term": "Managed solution", "certId": "pl400", "definition": "A Power Platform solution type where components are locked in the target environment (cannot be modified directly). Supports clean uninstall. Used for production deployments.", "definitionDe": "Ein Power Platform-Lösungstyp, bei dem Komponenten in der Zielumgebung gesperrt sind (können nicht direkt geändert werden). Unterstützt saubere Deinstallation. Für Produktionsbereitstellungen verwendet." },
  { "term": "Unmanaged solution", "certId": "pl400", "definition": "A Power Platform solution type where all components are fully editable. Used during development. Should not be deployed to production environments.", "definitionDe": "Ein Power Platform-Lösungstyp, bei dem alle Komponenten vollständig bearbeitbar sind. In der Entwicklung verwendet. Sollte nicht in Produktionsumgebungen bereitgestellt werden." },
  { "term": "ALM (Application Lifecycle Management)", "certId": "pl400", "definition": "The process of managing solution development from inception through deployment, including source control, environment strategy, testing, and release management.", "definitionDe": "Der Prozess der Verwaltung der Lösungsentwicklung von der Entstehung bis zur Bereitstellung, einschließlich Quellcodeverwaltung, Umgebungsstrategie, Tests und Release-Management." },
  { "term": "Power Platform Pipelines", "certId": "pl400", "definition": "Microsoft's built-in, low-code ALM tool for deploying Power Platform solutions between environments. The recommended starting point for release management.", "definitionDe": "Microsofts eingebautes, codeunabhängiges ALM-Tool zur Bereitstellung von Power Platform-Lösungen zwischen Umgebungen. Der empfohlene Ausgangspunkt für das Release-Management." },
  { "term": "Plug-in", "certId": "pl400", "definition": "A .NET assembly that executes custom business logic in Dataverse in response to events (Create, Update, Delete, etc.). Can run synchronously (within the transaction) or asynchronously.", "definitionDe": "Eine .NET-Assembly, die benutzerdefinierte Geschäftslogik in Dataverse als Antwort auf Ereignisse (Erstellen, Aktualisieren, Löschen usw.) ausführt. Kann synchron (innerhalb der Transaktion) oder asynchron ausgeführt werden." },
  { "term": "Pre-Operation stage (stage 20)", "certId": "pl400", "definition": "Plug-in execution stage that runs synchronously after security checks but before the database write, within the same transaction. Throwing an exception rolls back the operation.", "definitionDe": "Plug-in-Ausführungsstufe, die synchron nach Sicherheitsprüfungen, aber vor dem Datenbankschreiben ausgeführt wird, innerhalb derselben Transaktion. Das Auslösen einer Ausnahme rollt die Operation zurück." },
  { "term": "IOrganizationService", "certId": "pl400", "definition": "The primary Dataverse SDK interface in plug-ins for CRUD operations: Create, Retrieve, RetrieveMultiple, Update, Delete, Execute, Associate, Disassociate.", "definitionDe": "Das primäre Dataverse-SDK-Interface in Plug-ins für CRUD-Operationen: Create, Retrieve, RetrieveMultiple, Update, Delete, Execute, Associate, Disassociate." },
  { "term": "Virtual table", "certId": "pl400", "definition": "A Dataverse table that maps to external data via a data provider. The data is not stored in Dataverse — reads and writes are delegated to the external system in real time.", "definitionDe": "Eine Dataverse-Tabelle, die über einen Datenanbieter externen Daten zugeordnet ist. Die Daten werden nicht in Dataverse gespeichert — Lese- und Schreiboperationen werden in Echtzeit an das externe System delegiert." },
  { "term": "Alternate key", "certId": "pl400", "definition": "A Dataverse feature that designates one or more columns as unique identifiers. Enables referencing records by business keys (e.g., email) instead of GUIDs, and supports Web API upsert.", "definitionDe": "Eine Dataverse-Funktion, die eine oder mehrere Spalten als eindeutige Bezeichner festlegt. Ermöglicht das Referenzieren von Datensätzen anhand von Geschäftsschlüsseln (z.B. E-Mail) anstatt GUIDs und unterstützt Web API Upsert." },
  { "term": "Field-level security", "certId": "pl400", "definition": "A Dataverse security mechanism using column security profiles to restrict read, create, and update access to individual columns, independent of table-level security roles.", "definitionDe": "Ein Dataverse-Sicherheitsmechanismus, der Spaltensicherheitsprofile verwendet, um den Lese-, Erstell- und Aktualisierungszugriff auf einzelne Spalten einzuschränken, unabhängig von Sicherheitsrollen auf Tabellenebene." },
  { "term": "On-premises data gateway", "certId": "pl400", "definition": "A software agent installed on a local machine that acts as a secure bridge between Power Platform cloud services and on-premises data sources (SQL Server, SharePoint, Oracle) behind firewalls.", "definitionDe": "Ein Software-Agent, der auf einem lokalen Computer installiert ist und als sichere Brücke zwischen Power Platform-Cloud-Diensten und lokalen Datenquellen (SQL Server, SharePoint, Oracle) hinter Firewalls fungiert." },
  { "term": "Custom connector", "certId": "pl400", "definition": "A user-defined connector in Power Platform that wraps any REST or SOAP API, making it available as a native connector in Power Apps, Power Automate, and Logic Apps.", "definitionDe": "Ein benutzerdefinierter Connector in Power Platform, der eine beliebige REST- oder SOAP-API umhüllt und sie als nativen Connector in Power Apps, Power Automate und Logic Apps verfügbar macht." },
  { "term": "Environment variable", "certId": "pl400", "definition": "A Power Platform solution component that stores configuration values (text, number, boolean, secret) that can differ per environment. Values are provided at deployment time.", "definitionDe": "Eine Power Platform-Lösungskomponente, die Konfigurationswerte (Text, Zahl, Boolesch, Secret) speichert, die sich pro Umgebung unterscheiden können. Werte werden zum Bereitstellungszeitpunkt angegeben." },
  { "term": "OData (Open Data Protocol)", "certId": "pl400", "definition": "REST-based protocol used by the Dataverse Web API. Supports query options: $select, $filter, $expand, $orderby, $top, $skip, $count for querying and manipulating data.", "definitionDe": "REST-basiertes Protokoll, das von der Dataverse Web API verwendet wird. Unterstützt Abfrageoptionen: $select, $filter, $expand, $orderby, $top, $skip, $count zum Abfragen und Bearbeiten von Daten." },
  { "term": "Delegation (canvas apps)", "certId": "pl400", "definition": "The ability of a canvas app to push filter/sort/search operations to the data source (server-side). Non-delegable functions are processed client-side with a 500-record cap.", "definitionDe": "Die Fähigkeit einer Canvas App, Filter-/Sort-/Suchoperationen an die Datenquelle weiterzuleiten (serverseitig). Nicht delegierbare Funktionen werden clientseitig mit einer 500-Datensatz-Grenze verarbeitet." },
  { "term": "Business process flow (BPF)", "certId": "pl400", "definition": "A Power Platform feature that guides users through a defined sequence of stages on a Dataverse record form. Supports conditional branching based on field values.", "definitionDe": "Eine Power Platform-Funktion, die Benutzer durch eine definierte Abfolge von Stufen auf einem Dataverse-Datensatzformular führt. Unterstützt bedingte Verzweigungen basierend auf Feldwerten." },
  { "term": "Azure Relay", "certId": "pl400", "definition": "An Azure service that enables synchronous, bidirectional communication through firewalls. Unlike Service Bus (async), the caller waits for an immediate response — suitable for request-reply integration.", "definitionDe": "Ein Azure-Dienst, der synchrone, bidirektionale Kommunikation durch Firewalls ermöglicht. Anders als Service Bus (async) wartet der Aufrufer auf eine sofortige Antwort — geeignet für Request-Reply-Integration." },
  { "term": "AI Builder document processing", "certId": "pl400", "definition": "An AI Builder model type that extracts structured fields (invoice number, amounts, dates) from semi-structured documents like invoices and forms. Trained on sample documents.", "definitionDe": "Ein AI Builder-Modelltyp, der strukturierte Felder (Rechnungsnummer, Beträge, Daten) aus halbstrukturierten Dokumenten wie Rechnungen und Formularen extrahiert. Wird mit Beispieldokumenten trainiert." },
  { "term": "Upsert (Web API)", "certId": "pl400", "definition": "A Dataverse Web API operation (HTTP PATCH + alternate key) that creates a record if it doesn't exist or updates it if it does — combining two operations into one request.", "definitionDe": "Eine Dataverse Web API-Operation (HTTP PATCH + alternativer Schlüssel), die einen Datensatz erstellt, wenn er nicht existiert, oder ihn aktualisiert, wenn er existiert — kombiniert zwei Operationen in einer Anfrage." }
];
